# Number of trainable parameters:
dataset_reader:
  type: subwiki_network
  data_dir: "./data"
  fp16: false
train_data_path: train
validation_data_path: valid
test_data_path: test
vocabulary:
  type: empty
model:
  type: time_series_lstm_network_wiki
  agg_type: sage
  diff_type: last_week
  peak: true
  data_dir: "./data"
  decoder:
    type: lstm_decoder
    rnn:
      type: lstm
      batch_first: true
      stateful: true
      num_layers: 2
      bias: True
      bidirectional: false
    decoder_input_dim: 1
    hidden_size: 64
    dropout: 0.1
    dilation: 1
iterator:
  type: basic
  batch_size: 256
  cache_instances: false
  instances_per_epoch: 2097152
validation_iterator:
  type: basic
  batch_size: 256
  cache_instances: false
trainer:
  type: callback_apex
  apex_opt_level: O1
  keep_batchnorm_fp32: None
  optimizer:
    type: bert_adam
    lr: 0.0001
    weight_decay: 0.0001
    warmup: 0.05
    t_total: 163840 # 8192 batches per epoch
    max_grad_norm: 0.1
    parameter_groups:
      - - - project_in
        - {}
      - - - ^decoder.layers.0
        - {}
      - - - ^decoder.layers.1
        - {}
      - - - ^decoder.layers.2
        - {}
      - - - ^fc
        - {}
  num_epochs: 20
  cuda_device: 0
  shuffle: false
  callbacks:
    - type: checkpoint
    # - type: archive
    - type: track_metrics
      patience: 100
      validation_metric: "-loss"
    - type: validate
    - type: log_to_tensorboard
      summary_interval: 100
      should_log_parameter_statistics: false
      log_batch_size_period: 1000
