# Number of trainable parameters: 30701
dataset_reader:
  type: taxi
  series_path: data/taxi/sz_speed.csv # 2976 points at 15m intervals (31 days)
  train_p: 0.8
  seq_len: 4
  pre_len: 1
train_data_path: train
validation_data_path: valid
test_data_path: test
vocabulary:
  type: empty
model:
  type: tgcn
  adj_path: data/taxi/sz_adj.csv # 156 roads
  hidden_size: 100
  forecast_len: 1
  lambda_loss: 0.0015
  initializer:
    regexes:
      - - ^W_out.weight
        - type: normal
          mean: 1
      - - ^b_out
        - normal
      - - ^tgcn.*weight
        - xavier_uniform
data_loader:
  batch_size: 32
  shuffle: false
validation_data_loader:
  batch_size: 1024
trainer:
  type: apex_gradient_descent
  use_amp: false
  apex_opt_level: O0
  keep_batchnorm_fp32: None
  optimizer:
    type: adam
    lr: 0.001
  num_epochs: 5000
  cuda_device: 0
  patience: 1000
  validation_metric: "-rmse"
  tensorboard_writer:
    summary_interval: 100
    should_log_parameter_statistics: false
