name: radflow
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - autopep8=1.5.4
  - cudatoolkit=10.2.89
  - cython=0.29.21
  - ipykernel=5.3.4
  - matplotlib=3.3.1
  - mypy=0.782
  - numpy=1.19.1
  - pandas=1.1.1
  - pip=20.2.2
  - pytorch=1.6.0
  - python=3.8.5
  - pyyaml=5.3.1
  - redis-py=3.5.3
  - torchvision=0.7.0
  - pip:
      - allennlp==1.1.0rc4
      - pmdarima===1.7.0
      - bz2file==0.98
      - beautifulsoup4==4.9.1
      - docopt==0.6.2
      - docker==4.3.1
      - jina==0.5.0
      - overrides==3.1.0
      - ptvsd==4.3.2
      - pudb==2019.2
      - pyarrow==1.0.1
      - pymongo==3.11.0
      - redisgraph==2.1.4
      - schema==0.7.2
      - seaborn==0.10.1
      - tensorboard==2.3.0
      - tqdm==4.48.2
      - wget==3.2
      - wordcloud==1.8.0
