name: nos
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - autopep8=1.4.4
  - cudatoolkit=10.1.243
  - cython=0.29.15
  - ipykernel=5.1.4
  - matplotlib=3.1.3
  - mypy=0.750
  - numpy=1.17.2
  - opencv=4.2.0
  - pip=20.0.2
  - pandas=1.0.3
  - pytorch=1.4.0
  - python=3.7.4
  - pyyaml=5.1.2
  - tiledb-py
  - torchvision=0.5.0
  - pip:
      - allennlp==0.9.0
      - bz2file==0.98
      - beautifulsoup4==4.8.2
      - docopt==0.6.2
      - langdetect==1.0.7
      - nltk==3.4.5
      - overrides==2.8.0
      - Pillow==7.0.0
      - ptvsd==4.3.2
      - pudb==2019.2
      - git+git://github.com/salaniz/pycocoevalcap.git@a6b79b0fbd0f4f293634831e4e09405de2abc955
      - pymongo==3.10.1
      - pyzmq==19.0.0
      - schema==0.7.1
      - spacy==2.1.9
      - stop-words==2018.7.23
      - tensorboard==2.1.1
      - textstat==0.6.0
      - termcolor==1.1.0
      - tqdm==4.46.0
      - transformers==2.7.0
      - lxml==4.5.0
      - wget==3.2
