# Number of trainable parameters:
dataset_reader:
  type: subwiki_network
  data_dir: "./data/wiki/subgraphs"
  seed_word: vevo
  use_edge: true
  fp16: false
train_data_path: train
validation_data_path: valid
test_data_path: test
vocabulary:
  type: empty_vocab
model:
  type: nbeats_transformer
  data_dir: "./data/wiki/subgraphs"
  seed_word: vevo
  n_stacks: 8
  hidden_size: 128
  forecast_length: 7
  backcast_length: 35
  dropout: 0.1
  max_neighbours: 8
iterator:
  type: basic
  batch_size: 128
  cache_instances: false
  instances_per_epoch: 1048576
validation_iterator:
  type: basic
  batch_size: 128
  cache_instances: false
trainer:
  type: callback_apex
  apex_opt_level: O1
  keep_batchnorm_fp32: None
  optimizer:
    type: bert_adam
    lr: 0.00001
    weight_decay: 0.00001
    warmup: 0.05
    t_total: 163840 # 8192 batches per epoch
    max_grad_norm: 0.1
    parameter_groups:
      - - - project_in
        - {}
      - - - ^decoder.layers.0
        - {}
      - - - ^decoder.layers.1
        - {}
      - - - ^decoder.layers.2
        - {}
      - - - ^fc
        - {}
  num_epochs: 20
  cuda_device: 0
  shuffle: false
  callbacks:
    - type: checkpoint
    # - type: archive
    - type: track_metrics
      patience: 100
      validation_metric: "-loss"
    - type: validate
    - type: log_to_tensorboard
      summary_interval: 100
      should_log_parameter_statistics: false
      log_batch_size_period: 1000
