# Number of trainable parameters:
dataset_reader:
  type: subwiki_network
  train_path: data/wiki/node_ids/train_ids.pkl
  test_path: data/wiki/node_ids/test_ids.pkl
train_data_path: train
validation_data_path: valid
test_data_path: test
vocabulary:
  type: empty
model:
  type: nbeats_wiki
  data_path: ./data/wiki/wiki.hdf5
  series_len: 1827
  n_stacks: 8
  hidden_size: 176
  thetas_dims: 176
  forecast_length: 28
  backcast_length: 112
  test_lengths: [7, 14, 21, 28]
  dropout: 0.1
  max_neighbours: 0
data_loader:
  batch_size: 64
  shuffle: false
  batches_per_epoch: 10000
validation_data_loader:
  batch_size: 64
trainer:
  type: gradient_descent
  use_amp: false
  optimizer:
    type: adamw
    lr: 0.0001
    weight_decay: 0.0001
    parameter_groups:
      - - - ^net.stacks.0
        - {}
      - - - ^net.stacks.1
        - {}
      - - - ^net.stacks.2
        - {}
      - - - ^net.stacks.3
        - {}
      - - - ^net.stacks.4
        - {}
      - - - ^net.stacks.5
        - {}
      - - - ^net.stacks.6
        - {}
      - - - ^net.stacks.7
        - {}
  learning_rate_scheduler:
    type: linear_with_warmup
    warmup_steps: 5000
    last_epoch: -1
    num_steps_per_epoch: 10000
    num_epochs: 10
  num_epochs: 10
  cuda_device: 0
  grad_norm: 0.1
  callbacks:
    - type: checkpoint
    # - type: archive
    - type: track_metrics
      patience: 10
      validation_metric: "-smape_28"
    - type: validate
    - type: log_to_tensorboard
      summary_interval: 100
      should_log_parameter_statistics: false
      log_batch_size_period: 1000
