# Number of trainable parameters:
dataset_reader:
  type: subwiki_network
  train_path: data/wiki/node_ids/train_ids.pkl
  test_path: data/wiki/node_ids/test_ids.pkl
train_data_path: train
validation_data_path: valid
test_data_path: test
vocabulary:
  type: empty_vocab
model:
  type: baseline_agg_lstm_4
  data_path: ./data/wiki/wiki.hdf5
  key2pos_path: ./data/wiki/key2pos.pkl
  train_edges_ns: train_edges
  series_len: 1827
  agg_type: attention
  peek: true
  num_layers: 8
  hidden_size: 112
  dropout: 0.1
  forecast_length: 28
  backcast_length: 112
  test_lengths: [7, 14, 21, 28]
  max_neighbours: 4
  max_agg_neighbours: 4
  neigh_sample: true
  view_missing_p: 0
  view_randomize_p: false
  forward_fill: true
  n_hops: 2
  hop_scale: 1
  initializer:
    - - ^decoder.layers.*.layer.weight*
      - type: orthogonal
    - - ^decoder.layers.*.layer.bias
      - type: zero
iterator:
  type: basic
  batch_size: 64
  cache_instances: false
  instances_per_epoch: 524288
validation_iterator:
  type: basic
  batch_size: 64
  cache_instances: false
trainer:
  type: gradient_descent
  apex_opt_level: O1
  keep_batchnorm_fp32: None
  optimizer:
    type: adamw
    lr: 0.001
    weight_decay: 0.00025
    parameter_groups:
      - - - ^decoder.in_proj
        - {}
      - - - ^decoder.layers.0
        - {}
      - - - ^decoder.layers.1
        - {}
      - - - ^decoder.layers.2
        - {}
      - - - ^decoder.layers.3
        - {}
      - - - ^decoder.layers.4
        - {}
      - - - ^decoder.layers.5
        - {}
      - - - ^decoder.layers.6
        - {}
      - - - ^decoder.layers.7
        - {}
      - - - ^decoder.out_f
        - {}
      - - - ^attn
        - {}
      - - - ^fc
        - {}
  learning_rate_scheduler:
    type: linear_with_warmup
    warmup_steps: 5000
    last_epoch: -1
    num_steps_per_epoch: 8192
    num_epochs: 10
  num_epochs: 10
  cuda_device: 0
  grad_norm: 0.1
  shuffle: false
  callbacks:
    - type: checkpoint
    # - type: archive
    - type: track_metrics
      patience: 10
      validation_metric: "-smape_28"
    - type: validate
    - type: log_to_tensorboard
      summary_interval: 100
      should_log_parameter_statistics: false
      log_batch_size_period: 1000
