# Number of trainable parameters:
dataset_reader:
  type: taxi_2
  series_path: data/taxi/los_speed.csv # 2016 points at 5m intervals (7 days)
  seq_len: 36
  pre_len: 12
train_data_path: train
validation_data_path: valid
test_data_path: test
vocabulary:
  type: empty
model:
  type: tgcn
  adj_path: data/taxi/los_adj.csv # 207 roads
  hidden_size: 292
  forecast_len: 12
  initializer:
    regexes:
      - - ^W_out.weight
        - type: normal
          mean: 1
      - - ^b_out
        - normal
      - - ^tgcn.*weight
        - xavier_uniform
data_loader:
  batch_size: 64
  shuffle: false
  batches_per_epoch: 10000
validation_data_loader:
  batch_size: 1024 # current T-GCN metrics only work when we there's only one test batch
trainer:
  type: apex_gradient_descent
  use_amp: false
  apex_opt_level: O1
  keep_batchnorm_fp32: None
  optimizer:
    type: adamw
    lr: 0.0001
    weight_decay: 0.0001
  learning_rate_scheduler:
    type: linear_with_warmup
    warmup_steps: 5000
    last_epoch: -1
  num_epochs: 10
  cuda_device: 0
  patience: 1000
  validation_metric: "-smape"
  tensorboard_writer:
    summary_interval: 100
    should_log_parameter_statistics: false
