# Number of trainable parameters:
dataset_reader:
  type: network
  train_path: data/wiki/node_ids/train_ids.pkl
  test_path: data/wiki/node_ids/test_ids.pkl
train_data_path: train
validation_data_path: valid
test_data_path: test
vocabulary:
  type: empty
model:
  type: arima
  data_path: ./data/wiki/wiki.hdf5
  multi_views_path: ./data/wiki/views_split.hdf5
  forecast_length: 28
  backcast_length: 112
  test_lengths: [7, 14, 21, 28]
data_loader:
  batch_size: 32
  shuffle: false
  batches_per_epoch: 10000
validation_data_loader:
  batch_size: 32
trainer:
  type: apex_gradient_descent
  use_amp: false
  apex_opt_level: O1
  keep_batchnorm_fp32: None
  optimizer:
    type: adamw
    lr: 0.0001
    weight_decay: 0.0001
  learning_rate_scheduler:
    type: linear_with_warmup
    warmup_steps: 5000
    last_epoch: -1
  num_epochs: 10
  cuda_device: 0
  grad_norm: 0.1
  patience: 10
  validation_metric: "-loss"
  tensorboard_writer:
    summary_interval: 100
    should_log_parameter_statistics: false
