# Number of trainable parameters:
dataset_reader:
  type: subwiki_network
  train_path: data/wiki/node_ids/train_ids.pkl
  test_path: data/wiki/node_ids/test_ids.pkl
train_data_path: train
validation_data_path: valid
test_data_path: test
vocabulary:
  type: empty
model:
  type: baseline_agg_lstm_2
  data_path: ./data/wiki/wiki.hdf5
  key2pos_path: ./data/wiki/key2pos.pkl
  test_keys_path: ./data/wiki/node_ids/test_ids.pkl
  series_len: 1827
  agg_type: none
  peek: true
  num_layers: 8
  hidden_size: 164
  dropout: 0.1
  backcast_length: 112
  forecast_length: 28
  test_lengths: [7, 14, 21, 28]
  initializer:
    - - ^decoder.weight*
      - type: orthogonal
    - - ^decoder.bias*
      - type: zero
data_loader:
  batch_sampler:
    type: basic
    batch_size: 64
    cache_instances: false
    instances_per_epoch: 524288
validation_data_loader:
  batch_sampler:
    type: basic
    batch_size: 64
    cache_instances: false
trainer:
  type: gradient_descent
  use_amp: true
  optimizer:
    type: adamw
    lr: 0.001
    weight_decay: 0.00025
    parameter_groups:
      - - - ^decoder
        - {}
      - - - ^fc
        - {}
  learning_rate_scheduler:
    type: linear_with_warmup
    warmup_steps: 5000
    last_epoch: -1
    num_steps_per_epoch: 8192
    num_epochs: 10
  num_epochs: 10
  cuda_device: 0
  grad_norm: 0.1
  shuffle: false
  callbacks:
    - type: checkpoint
    # - type: archive
    - type: track_metrics
      patience: 10
      validation_metric: "-smape_28"
    - type: validate
    - type: log_to_tensorboard
      summary_interval: 100
      should_log_parameter_statistics: false
      log_batch_size_period: 1000
