# Number of trainable parameters:
dataset_reader:
  type: subwiki_network
  train_path: data/vevo/vevo_connected_nodes.pkl
  test_path: data/vevo/vevo_connected_nodes.pkl
train_data_path: train
validation_data_path: valid
test_data_path: test
vocabulary:
  type: empty
model:
  type: new_naive
  method: previous_day
  forecast_length: 7
  backcast_length: 42
data_loader:
  batch_size: 64
  shuffle: false
  batches_per_epoch: 10000
validation_data_loader:
  batch_size: 64
trainer:
  type: gradient_descent
  use_amp: true
  optimizer:
    type: adamw
    lr: 0.001
    weight_decay: 0.00025
    parameter_groups:
      - - - project_in
        - {}
      - - - ^decoder.layers.0
        - {}
      - - - ^decoder.layers.1
        - {}
      - - - ^decoder.layers.2
        - {}
      - - - ^fc
        - {}
  learning_rate_scheduler:
    type: linear_with_warmup
    warmup_steps: 5000
    last_epoch: -1
    num_steps_per_epoch: 10000
    num_epochs: 10
  num_epochs: 10
  cuda_device: 0
  grad_norm: 0.1
  patience: 10
  validation_metric: "-smape_7"
  tensorboard_writer:
    summary_interval: 100
    should_log_parameter_statistics: false
