# Number of trainable parameters:
dataset_reader:
  type: taxi
  series_path: data/taxi/los_speed.csv # 2016 points at 5m intervals (7 days)
  train_p: 0.8
  seq_len: 36
  pre_len: 12
train_data_path: train
validation_data_path: valid
test_data_path: test
vocabulary:
  type: empty
model:
  type: tgcn
  adj_path: data/taxi/los_adj.csv # 207 roads
  hidden_size: 128 # 50,436 parameters
  forecast_len: 12
  initializer:
    regexes:
      - - ^W_out.weight
        - type: normal
          mean: 1
      - - ^b_out
        - normal
      - - ^tgcn.*weight
        - xavier_uniform
data_loader:
  batch_size: 64
  shuffle: false
  batches_per_epoch: 10000
validation_data_loader:
  batch_size: 1024
trainer:
  type: apex_gradient_descent
  use_amp: false
  apex_opt_level: O0
  keep_batchnorm_fp32: None
  optimizer:
    type: adamw
    lr: 0.001
    weight_decay: 0.0015
  num_epochs: 10
  cuda_device: 0
  grad_norm: 0.1
  patience: 1000
  validation_metric: "-loss"
  tensorboard_writer:
    summary_interval: 100
    should_log_parameter_statistics: false
