# Number of trainable parameters:
dataset_reader:
  type: subwiki
  data_dir: "./data"
  seed_word: Star Wars
  remove_trends: true
  fp16: false
train_data_path: train
validation_data_path: valid
test_data_path: test
vocabulary:
  type: empty
model:
  type: naive_seasonal
  n_days: 62
iterator:
  type: basic
  batch_size: 64
  instances_per_epoch: 4096
  cache_instances: false
validation_iterator:
  type: basic
  batch_size: 64
  cache_instances: false
trainer:
  type: callback_apex
  apex_opt_level: O0
  keep_batchnorm_fp32: None
  optimizer:
    type: bert_adam
    lr: 0.0001
    weight_decay: 0.0001
    warmup: 0.05
    t_total: 204800 # 2048 batches per epoch
    max_grad_norm: 0.1
    parameter_groups:
      - - - project_in
        - {}
      - - - ^decoder.layers.0
        - {}
      - - - ^decoder.layers.1
        - {}
      - - - ^decoder.layers.2
        - {}
      - - - ^fc
        - {}
  num_epochs: 100
  cuda_device: 0
  shuffle: false
  callbacks:
    - type: checkpoint
    # - type: archive
    - type: track_metrics
      patience: 100
      validation_metric: "-loss"
    - type: validate
    - type: log_to_tensorboard
      summary_interval: 100
      should_log_parameter_statistics: false
      log_batch_size_period: 1000
