# Number of trainable parameters: 30662
dataset_reader:
  type: taxi
  series_path: data/taxi/sz_speed.csv # 2976 points at 15m intervals (31 days)
  train_p: 0.8
  seq_len: 4
  pre_len: 1
train_data_path: train
validation_data_path: valid
test_data_path: test
vocabulary:
  type: empty
model:
  type: radflow_taxi
  adj_path: data/taxi/sz_adj.csv # 156 roads
  hidden_size: 35
  forecast_len: 1
  n_layers: 2
  dropout: 0.2
  variant: none
data_loader:
  batch_size: 64
  shuffle: false
  batches_per_epoch: 10000
validation_data_loader:
  batch_size: 1024
trainer:
  type: apex_gradient_descent
  use_amp: false
  apex_opt_level: O0
  keep_batchnorm_fp32: None
  optimizer:
    type: adamw
    lr: 0.0001
    weight_decay: 0.0001
  learning_rate_scheduler:
    type: linear_with_warmup
    warmup_steps: 5000
    last_epoch: -1
  num_epochs: 20
  cuda_device: 0
  grad_norm: 0.1
  patience: 1000
  validation_metric: "-rmse"
  tensorboard_writer:
    summary_interval: 100
    should_log_parameter_statistics: false
