# Number of trainable parameters:
dataset_reader:
  type: network
  train_path: data/vevo/vevo_connected_nodes.pkl
  test_path: data/vevo/vevo_connected_nodes.pkl
train_data_path: train
validation_data_path: valid
test_data_path: test
vocabulary:
  type: empty
model:
  type: radflow
  agg_type: mean
  data_path: ./data/vevo/vevo_static.hdf5
  key2pos_path: ./data/vevo/vevo_static.key2pos.pkl
  peek: true
  num_layers: 8
  hidden_size: 120
  dropout: 0.1
  forecast_length: 7
  backcast_length: 42
  test_lengths: [7]
  max_neighbours: 4
  max_agg_neighbours: 4
  max_eval_neighbours: 8
  neigh_sample: true
  n_hops: 2
  hop_scale: 1
  base_model_config: expt/reports/vevo/no_hops/flow_lstm/config.yaml
  base_model_weights: expt/reports/vevo/no_hops/flow_lstm/serialization/model_state_epoch_9.th
  initializer:
    regexes:
      - - ^decoder.layers.*.layer.weight*
        - orthogonal
      - - ^decoder.layers.*.layer.bias
        - zero
data_loader:
  batch_size: 64
  shuffle: false
  batches_per_epoch: 10000
validation_data_loader:
  batch_size: 64
trainer:
  type: apex_gradient_descent
  use_amp: false
  apex_opt_level: O1
  keep_batchnorm_fp32: None
  optimizer:
    type: adamw
    lr: 0.0001
    weight_decay: 0.0001
    parameter_groups:
      - - - ^decoder.in_proj
        - {}
      - - - ^decoder.layers.0
        - {}
      - - - ^decoder.layers.1
        - {}
      - - - ^decoder.layers.2
        - {}
      - - - ^decoder.layers.3
        - {}
      - - - ^decoder.layers.4
        - {}
      - - - ^decoder.layers.5
        - {}
      - - - ^decoder.layers.6
        - {}
      - - - ^decoder.layers.7
        - {}
      - - - ^decoder.out_f
        - {}
      - - - ^attn
        - {}
      - - - ^fc
        - {}
  learning_rate_scheduler:
    type: linear_with_warmup
    warmup_steps: 5000
    last_epoch: -1
  num_epochs: 10
  cuda_device: 0
  grad_norm: 0.1
  patience: 10
  validation_metric: "-smape_7"
  tensorboard_writer:
    summary_interval: 100
    should_log_parameter_statistics: false
