# Number of trainable parameters:
dataset_reader:
  type: subwiki_network
  train_path: data/vevo/vevo_all_nodes.pkl
  test_path: data/vevo/vevo_connected_nodes.pkl
train_data_path: train
validation_data_path: valid
test_data_path: test
vocabulary:
  type: empty
model:
  type: nbeats_wiki
  n_stacks: 8
  hidden_size: 192
  thetas_dims: 192
  forecast_length: 7
  backcast_length: 42
  test_lengths: [7]
  dropout: 0.1
  max_neighbours: 0
data_loader:
  batch_sampler:
    type: basic
    batch_size: 64
    cache_instances: false
    instances_per_epoch: 524288
validation_data_loader:
  batch_sampler:
    type: basic
    batch_size: 64
    cache_instances: false
trainer:
  type: gradient_descent
  use_amp: true
  optimizer:
    type: adamw
    lr: 0.001
    weight_decay: 0.00025
    parameter_groups:
      - - - ^net.stacks.0
        - {}
      - - - ^net.stacks.1
        - {}
      - - - ^net.stacks.2
        - {}
      - - - ^net.stacks.3
        - {}
      - - - ^net.stacks.4
        - {}
      - - - ^net.stacks.5
        - {}
      - - - ^net.stacks.6
        - {}
      - - - ^net.stacks.7
        - {}
  learning_rate_scheduler:
    type: linear_with_warmup
    warmup_steps: 5000
    last_epoch: -1
    num_steps_per_epoch: 8192
    num_epochs: 10
  num_epochs: 10
  cuda_device: 0
  grad_norm: 0.1
  shuffle: false
  patience: 10
  validation_metric: "-smape_7"
  tensorboard_writer:
    summary_interval: 100
    should_log_parameter_statistics: false
