# Number of trainable parameters:
dataset_reader:
  type: subwiki_network
  train_path: data/vevo/vevo_all_nodes.pkl
  test_path: data/vevo/vevo_connected_nodes.pkl
train_data_path: train
validation_data_path: valid
test_data_path: test
vocabulary:
  type: empty_vocab
model:
  type: nbeats_wiki
  n_stacks: 8
  hidden_size: 192
  thetas_dims: 192
  forecast_length: 7
  backcast_length: 42
  test_lengths: [7]
  dropout: 0.1
  max_neighbours: 0
iterator:
  type: basic
  batch_size: 64
  cache_instances: false
  instances_per_epoch: 524288
validation_iterator:
  type: basic
  batch_size: 64
  cache_instances: false
trainer:
  type: callback_apex
  apex_opt_level: O1
  keep_batchnorm_fp32: None
  optimizer:
    type: adamw
    lr: 0.001
    weight_decay: 0.00025
    parameter_groups:
      - - - ^net.stacks.0
        - {}
      - - - ^net.stacks.1
        - {}
      - - - ^net.stacks.2
        - {}
      - - - ^net.stacks.3
        - {}
      - - - ^net.stacks.4
        - {}
      - - - ^net.stacks.5
        - {}
      - - - ^net.stacks.6
        - {}
      - - - ^net.stacks.7
        - {}
  learning_rate_scheduler:
    type: linear_with_warmup
    warmup_steps: 5000
    last_epoch: -1
    num_steps_per_epoch: 8192
    num_epochs: 10
  num_epochs: 10
  cuda_device: 0
  grad_norm: 0.1
  shuffle: false
  callbacks:
    - type: checkpoint
    # - type: archive
    - type: track_metrics
      patience: 10
      validation_metric: "-smape_7"
    - type: validate
    - type: log_to_tensorboard
      summary_interval: 100
      should_log_parameter_statistics: false
      log_batch_size_period: 1000
