# Number of trainable parameters:
dataset_reader:
  type: network
  n_nodes: 156
train_data_path: train
validation_data_path: valid
test_data_path: test
vocabulary:
  type: empty
model:
  type: naive
  method: previous_day
  data_path: data/taxi/sz.h5
  series_len: 2976
  forecast_length: 4
  backcast_length: 24
  test_lengths: [4]
  ignore_test_zeros: true
data_loader:
  batch_size: 64
  shuffle: false
  batches_per_epoch: 10000
validation_data_loader:
  batch_size: 64
trainer:
  type: apex_gradient_descent
  use_amp: false
  apex_opt_level: O1
  keep_batchnorm_fp32: None
  optimizer:
    type: adamw
    lr: 0.0001
    weight_decay: 0.0001
  learning_rate_scheduler:
    type: linear_with_warmup
    warmup_steps: 5000
    last_epoch: -1
  num_epochs: 10
  cuda_device: 0
  grad_norm: 0.1
  patience: 10
  validation_metric: "-smape_4"
  tensorboard_writer:
    summary_interval: 100
    should_log_parameter_statistics: false
